function [Matrix] = nastranOutputReader(filename)

% Read OUTPUT4 fromat files of mass (M) and stiffness (K) matrices generated by NASTRAN
file = importdata(filename);
data = file.data;
header = sscanf(file.textdata{1}, '%d %d %d %d', [1, 4]);
[cols, rows] = deal(header(1), header(2));
matrix = zeros(rows, cols);

for i = 1:length(data)-1
    nz_row_i = nonzeros(data(i,:))';
    if ~isempty(nz_row_i) && isequal(floor(nz_row_i), nz_row_i)
        if i > 1
            temp(isnan(temp)) = 0;
            matrix(row:row+length(temp)-1, col) = temp;
        end
        [col, row] = deal(data(i,1), data(i,2));
        temp = [];
    else
        temp = [temp; data(i,:)'];
    end
end

Matrix = matrix;

end
